// The dial audit: every [Proposed] and [Assumed] number, where it lives and what it says. Settled [Doc] dials are left out.
//   npm run dials > DIALS.md

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const FILES = ['src/rules.ts', 'src/actions.ts', 'src/hatch.ts'];
const root = fileURLToPath(new URL('..', import.meta.url));
const rows: Record<'Proposed' | 'Assumed', string[]> = { Proposed: [], Assumed: [] };

for (const file of FILES) {
  const lines = readFileSync(root + file, 'utf8').split('\n');
  const start = lines.findIndex((l) => l.startsWith('export') || /^const /.test(l));
  lines.forEach((line, i) => {
    // Skip the legend above the first declaration, and section headers.
    if (i < start || /^\s*\/\/ ----/.test(line)) return;
    const tags = (['Proposed', 'Assumed'] as const).filter((t) => line.includes(`[${t}`));
    if (!tags.length) return;
    // A comment-only line describes the dial that follows it.
    let at = i;
    while (/^\s*\/\//.test(lines[at]) && at + 1 < lines.length) at++;
    const key = /^\s*(?:export\s+const\s+)?([A-Za-z_][\w]*)\s*[:=]/.exec(lines[at])?.[1] ?? '—';
    const text = (line.includes('//') ? line.slice(line.indexOf('//') + 2) : line).trim().replace(/\|/g, '\\|');
    for (const t of tags) rows[t].push(`| \`${key}\` | ${text} | \`${file}:${i + 1}\` |`);
  });
}

console.log('# Dial audit\n');
console.log('Generated by `npm run dials`. Every number still marked [Proposed] (suggested, not yet confirmed) or [Assumed] (a placeholder this build needed). When one settles, drop its tag here and in the design doc.\n');
for (const t of ['Proposed', 'Assumed'] as const) {
  console.log(`## [${t}] (${rows[t].length})\n`);
  console.log('| Dial | Note | Where |\n|---|---|---|');
  console.log(rows[t].join('\n') + '\n');
}
